### ISSUE TITLE
using SAM-Med2D-256x(ViT-Base) model to annotate demo_medical.png as readme.md shows but raise errors

### ISSUE THREAD

**Issue by cqray1990** [CVHub520/X-AnyLabeling#142]
WARNING:root:Could not inference model
WARNING:root:new style getargs format but argument is not a tuple
Traceback (most recent call last):
  File "X-AnyLabeling/./anylabeling/services/auto_labeling/sam_med2d.py", line 381, in predict_shapes
    image_embedding = self.model.encode(cv_image)
  File "X-AnyLabeling/./anylabeling/services/auto_labeling/sam_med2d.py", line 85, in encode
    self.encoder_input_name: self.transform(cv_image),
  File "X-AnyLabeling/./anylabeling/services/auto_labeling/sam_med2d.py", line 67, in transform
    input_image = cv2.resize(
SystemError: new style getargs format but argument is not a tuple
WARNING:root:Could not inference model
WARNING:root:new style getargs format but argument is not a tuple
Traceback (most recent call last):
  File "X-AnyLabeling/./anylabeling/services/auto_labeling/sam_med2d.py", line 381, in predict_shapes
    image_embedding = self.model.encode(cv_image)
  File "X-AnyLabeling/./anylabeling/services/auto_labeling/sam_med2d.py", line 85, in encode
    self.encoder_input_name: self.transform(cv_image),
  File "X-AnyLabeling/./anylabeling/services/auto_labeling/sam_med2d.py", line 67, in transform
    input_image = cv2.resize(
SystemError: new style getargs format but argument is not a tuple

**Comment by CVHub520** [comment]
Hello, @cqray1990,

Before using your custom SAM-Med2D-256x ONNX model, please ensure to check its input_shape, which should be in the [1, c, h, w] format. Here's an example:

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/21fc1f64-634e-4b2a-b2b7-9b2fe8717094)

For additional guidance, you can refer to this [repository](https://github.com/CVHub520/efficientvit#benchmarking-with-onnxruntime) for exporting your custom model accurately.

**Comment by cqray1990** [comment]
the demo_medical.png is in repository,model is loaded as  auto download, if model is ok, the input_shape should be resized as the right input _shape, it did not need modify the code. did u test the newest code to annotate the demo_medical.png?

**Comment by CVHub520** [comment]
Would u inference other model successfully?

**Comment by CVHub520** [comment]
This issue will be closed because it has been marked as invalid or awaiting response for 7 days without any further response.
