### ISSUE TITLE
Application Crash: TypeError on Concatenating String and Integer

### ISSUE THREAD

**Issue by gaigaimm** [CVHub520/X-AnyLabeling#411]
Traceback (most recent call last):
  File "app.py", line 229, in <module>
  File "app.py", line 209, in main
  File "views\mainwindow.py", line 30, in __init__
  File "views\labeling\label_wrapper.py", line 24, in __init__
  File "views\labeling\label_widget.py", line 1299, in __init__
  File "views\labeling\widgets\auto_labeling\auto_labeling.py", line 57, in __init__
  File "views\labeling\widgets\auto_labeling\auto_labeling.py", line 134, in update_model_configs
TypeError: can only concatenate str (not "int") to str

**Comment by CVHub520** [comment]
您好，可以删除用户目录下的 .anylabelingrc 文件后再尝试重启。

**Comment by gaigaimm** [comment]
发送失败，请稍后再发

**Comment by gaigaimm** [comment]
发送失败，请稍后再发
