### ISSUE TITLE
Error with cv2.findContours() function

### ISSUE THREAD

**Issue by DoongLi** [CVHub520/X-AnyLabeling#439]
errors below:
python anylabeling/app.py
WARNING:root:Could not inference model
WARNING:root:too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/home/doongli/X-AnyLabeling/X-AnyLabeling/./anylabeling/services/auto_labeling/segment_anything.py", line 263, in predict_shapes
    shapes = self.post_process(masks, cv_image)
  File "/home/doongli/X-AnyLabeling/X-AnyLabeling/./anylabeling/services/auto_labeling/segment_anything.py", line 129, in post_process
    contours, _ = cv2.findContours(
ValueError: too many values to unpack (expected 2)
WARNING:root:Could not inference model
WARNING:root:too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/home/doongli/X-AnyLabeling/X-AnyLabeling/./anylabeling/services/auto_labeling/segment_anything.py", line 263, in predict_shapes
    shapes = self.post_process(masks, cv_image)
  File "/home/doongli/X-AnyLabeling/X-AnyLabeling/./anylabeling/services/auto_labeling/segment_anything.py", line 129, in post_process
    contours, _ = cv2.findContours(
ValueError: too many values to unpack (expected 2)
WARNING:root:Could not inference model
WARNING:root:too many values to unpack (expected 2)

Solution below:
(It is best to refer to https://github.com/cvhub520/x-anylabeling/isSues/378 new virtual environment) then:
pip uninstall opencv-contrib-python-headless
pip install opencv-contrib-python-headless==4.7.0.72

**Comment by CVHub520** [comment]
Thank you for reporting this issue and providing a potential solution to the issue.
