### ISSUE TITLE
请问支持在arm64架构上的ubuntu20.04操作系统运行吗

### ISSUE THREAD

**Issue by GZhengyang** [CVHub520/X-AnyLabeling#456]

**Comment by GZhengyang** [comment]
只运行CPU版本的，尝试安装requirements.txt，其中pyqt5直接安装有问题`(11) [ma-user X-AnyLabeling-main]$pip install PyQt5==5.15.7
Looking in indexes: http://192.168.0.14:8888/repository/pypi/simple
Collecting PyQt5==5.15.7
  Using cached http://192.168.0.14:8888/repository/pypi/packages/pyqt5/5.15.7/PyQt5-5.15.7.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
      Traceback (most recent call last):
        File "/home/ma-user/anaconda3/envs/11/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/ma-user/anaconda3/envs/11/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ma-user/anaconda3/envs/11/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-ff7dwr7k/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/tmp/pip-build-env-ff7dwr7k/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 92, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-ff7dwr7k/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 587, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 69, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-ff7dwr7k/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 51, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-ff7dwr7k/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-ff7dwr7k/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 50, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by CVHub520** [comment]
您好，Pyqt5本身是跨平台的，理论上可以在多种不同的架构和操作系统上运行，包括ARM64。您这边可以尝试搜索如何在 ARM64 架构上安装编译 Pyqt5，确保该库能被正常安装使用，再执行 `pip install -r xxx`.
