### ISSUE TITLE
分类标注的相关问题

### ISSUE THREAD

**Issue by elichan5168** [CVHub520/X-AnyLabeling#480]
你好, 

我想问一些问题。

1. 我有一个数据集图片需要先分类，想问X-Anylabeling能不能只做图片分类的标签，而不用把物体定位框(bbox)画出来呢？我没找到直接打标签的地方? (现在版本似乎必需要先定位才能选择分类标签)
和https://github.com/cvat-ai/cvat/issues/1465 (这个问题比较类似)

2. 我还有另一个数据集，这个数据集只做了分类的标签，所以我想用X-Anylabeling先导入这部分已经分类好的分类标签，然后我再手动进行定位框的操作。这可以做到吗？（由于数据量太大，如果可以能节省很多时间）

3. 另外我还发现一个bug.  在win10上我用的requirements-gpu.txt安装后加载模型会闪退。ubuntu不会。
```
PS D:\X-AnyLabeling> python .\anylabeling\app.py
Traceback (most recent call last):
  File "D:\X-AnyLabeling\anylabeling\utils.py", line 15, in run
    self.func(*self.args, **self.kwargs)
  File "D:\X-AnyLabeling\anylabeling\services\auto_labeling\model_manager.py", line 687, in _load_model
    from .grounding_dino import Grounding_DINO
  File "D:\X-AnyLabeling\anylabeling\services\auto_labeling\grounding_dino.py", line 18, in <module>
    from .engines.build_onnx_engine import OnnxBaseModel
  File "D:\X-AnyLabeling\anylabeling\services\auto_labeling\engines\__init__.py", line 1, in <module>
    from .build_onnx_engine import OnnxBaseModel
  File "D:\X-AnyLabeling\anylabeling\services\auto_labeling\engines\build_onnx_engine.py", line 3, in <module>
    import onnxruntime as ort
  File "C:\Users\elich\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "C:\Users\elich\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elich\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing onnxruntime_pybind11_state: 动态链接库(DLL)初始化例程失败。

```
然后我win10把onnxruntime-gpu降到1.16.0版本就解决了.

谢谢。

**Comment by elichan5168** [comment]
@CVHub520 Thx, the issue is resolved. Looking forward to you adding the image classification mode in the future.

**Comment by CVHub520** [comment]
Hi @69101jda,

We're thrilled to share some exciting news! 🎉 We've recently introduced a brand new image classification experience in X-AnyLabeling, which we believe directly addresses your previous request. Thank you so much for your patience and continued support!

You can find all the details and a comprehensive tutorial [here](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/image_classifier.md)

We hope you'll find this new feature helpful! Please feel free to share any feedback. 😊
