### ISSUE TITLE
打开文件夹后报错，软件闪退

### ISSUE THREAD

**Issue by ChaXxl** [CVHub520/X-AnyLabeling#734]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

~~~text
Traceback (most recent call last):
  File "/Users/xxl/Code/Python/X-AnyLabeling/anylabeling/views/labeling/label_widget.py", line 6069, in open_folder_dialog
    self.import_image_folder(target_dir_path)
  File "/Users/xxl/Code/Python/X-AnyLabeling/anylabeling/views/labeling/label_widget.py", line 6125, in import_image_folder
    for filename in self.scan_all_images(dirpath):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxl/Code/Python/X-AnyLabeling/anylabeling/views/labeling/label_widget.py", line 6157, in scan_all_images
    images = natsort.os_sorted(images)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/natsort/natsort.py", line 929, in os_sorted
    return sorted(seq, key=os_sort_keygen(key), reverse=reverse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/natsort/utils.py", line 334, in natsort_key
    return string_func(cast(str, val))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/natsort/utils.py", line 536, in <lambda>
    return lambda x: tuple(map(str_split, path_splitter(x)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/natsort/utils.py", line 507, in func
    return final_transform(g, original)  # Apply the final transform.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/natsort/utils.py", line 760, in func
    return tuple(split_val)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/natsort/utils.py", line 561, in sep_inserter
    first = next(iterator)
            ^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/natsort/compat/fake_fastnumbers.py", line 118, in fast_int
    return _uni(x, key(x)) if len(x) == 1 else key(x)
                                               ^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/natsort/utils.py", line 825, in <lambda>
    return partial(reduce, lambda res, f: f(res), functions)
                                          ^^^^^^
OSError: [Errno 22] Invalid argument
[1]    70023 abort      python anylabeling/app.py
~~~

### Information

执行
~~~shell
python anylabeling/app.py
~~~

点击打开文件夹，选择后就报错：
<img width="541" alt="image" src="https://github.com/user-attachments/assets/11b8aefe-fabc-42c4-9b82-be7841d09f37">

### Link to a Reproducible Demonstration Video

https://github.com/user-attachments/assets/ecc5533a-ec41-4b36-a7b1-981798eeb1fa

### Execution Mode

Source Code

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Please carefully check if your file path has the following issues:  
1. Illegal characters;  
2. Spaces within the file name;  
3. Chinese characters.  

Specifically, you can insert a debug statement like `logger.info(images)` at the corresponding location [[here](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/views/labeling/label_widget.py#L6145-L6158)](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/views/labeling/label_widget.py#L6145-L6158) to log detailed information for more context.

**Comment by ChaXxl** [comment]
我的路径确实有中文，但我发现用命令行运行它就会报错，但如果用 PyCharm 运行就是正常的

https://github.com/user-attachments/assets/cc7bca78-c9d2-46e1-9cef-a9694195bac9

**Comment by CVHub520** [comment]
Thank's for your feekback! The error occurs when running the code from command line but works fine in PyCharm. This is likely due to path handling differences in different environments. Here's the modified code with better path handling and error management:

```python
# anylabeling/views/labeling/label_widget.py#6155
def scan_all_images(self, folder_path):
    try:
        extensions = [
            f".{fmt.data().decode().lower()}"
            for fmt in QtGui.QImageReader.supportedImageFormats()
        ]

        images = []
        # Normalize root path
        folder_path = osp.normpath(osp.abspath(folder_path))

        for root, _, files in os.walk(folder_path):
            for file in files:
                if file.lower().endswith(tuple(extensions)):
                    relative_path = osp.normpath(osp.join(root, file))
                    relative_path = str(relative_path)
                    images.append(relative_path)

        try:
            return natsort.os_sorted(images)
        except (OSError, ValueError) as e:
            logger.warning(f"Warning: Natural sort failed, falling back to regular sort: {e}")
            return sorted(images)

    except Exception as e:
        logger.error(f"Error scanning images: {e}")
        return []
```

You are able to test this and report your testing outcome here.
