### ISSUE TITLE
可以正确加载自定义模型，运行自动标注的时候会闪退。

### ISSUE THREAD

**Issue by 377343577** [CVHub520/X-AnyLabeling#753]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

![381df9ab9c7a4966f34f80463e143b42](https://github.com/user-attachments/assets/4c280447-57cb-4ba3-a6df-de6327961e4a)

### Information

2.5.1版本

### Link to a Reproducible Demonstration Video

![381df9ab9c7a4966f34f80463e143b42](https://github.com/user-attachments/assets/77c9e48c-a47a-47ff-b599-9a2f0d4c50d4)

### Execution Mode

Pre-compiled Executable

### Additional

2024-12-21 12:23:50,767 | INFO    | app:main:159 - 🚀 X-AnyLabeling v2.5.0 launched!
2024-12-21 12:23:50,767 | INFO    | app:main:162 - ⭐ If you like it, give us a star: https://github.com/CVHub520/X-AnyLabeling
2024-12-21 12:23:50,783 | INFO    | config:get_config:83 - 🔧️ Initializing config from local file: C:\Users\37734\.xanylabelingrc
2024-12-21 12:24:22,596 | INFO    | model_manager:_load_model:378 - ✅ Model loaded successfully: yolov5
Traceback (most recent call last):
  File "C:\Users\37734\PycharmProjects\pythonProject\X-AnyLabeling-2.5.1\.\anylabeling\views\labeling\widgets\canvas.py", line 1181, in paintEvent
    shape.paint(p)
  File "C:\Users\37734\PycharmProjects\pythonProject\X-AnyLabeling-2.5.1\.\anylabeling\views\labeling\shape.py", line 250, in paint
    assert len(self.points) in [1, 2, 4]
AssertionError

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Please verify your custom configuration file.
