### ISSUE TITLE
导出时崩溃

### ISSUE THREAD

**Issue by Consulting4J** [CVHub520/X-AnyLabeling#766]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Export/Import

### Bug

导出为YOLO关键点标签

### Information

2024-12-29 14:48:26,845 | INFO    | app:main:159 - 🚀 X-AnyLabeling v2.5.0 launched!
2024-12-29 14:48:26,845 | INFO    | app:main:162 - ⭐ If you like it, give us a star: https://github.com/CVHub520/X-AnyLabeling
2024-12-29 14:48:26,861 | INFO    | config:get_config:83 - 🔧️ Initializing config from local file: /a/xxx/.xanylabelingrc
Traceback (most recent call last):
  File "/home/runner/X-AnyLabeling/anylabeling/views/labeling/label_widget.py", line 1071, in <lambda>
    lambda: self.export_yolo_annotation("pose"),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/X-AnyLabeling/anylabeling/views/labeling/label_widget.py", line 4703, in export_yolo_annotation
    converter = LabelConverter(pose_cfg_file=self.yaml_file)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/X-AnyLabeling/anylabeling/views/labeling/label_converter.py", line 35, in __init__
    self.has_vasiable = data["has_visible"]
                        ~~~~^^^^^^^^^^^^^^^
KeyError: 'has_visible'
Aborted (core dumped)


### Link to a Reproducible Demonstration Video

导出为YOLO关键点标签

### Execution Mode

Source Code

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hello, please ensure that the `has_visible` field is present in the exported configuration file. For detailed instructions on export settings, please refer to this [section](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#41-yolo%E6%A0%87%E7%AD%BE). Similarly, you can browse related posts: #471.
